// <auto-generated />
using System;
using ChamaJussaAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChamaJussaAPI.Migrations
{
    [DbContext(typeof(ChamaJussaContext))]
    [Migration("20260730131121_ChamaJussa")]
    partial class ChamaJussa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChamaJussaAPI.Domains.OrdemDeServico", b =>
                {
                    b.Property<int>("os_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("os_id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("dt_criacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("fila")
                        .HasColumnType("int");

                    b.Property<string>("imagem")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("localizacao_id")
                        .HasColumnType("int");

                    b.Property<string>("nome_item")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("solicitante")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.HasKey("os_id")
                        .HasName("PK__OrdemDeS__374FA4B502ACC0D3");

                    b.HasIndex("fila");

                    b.HasIndex("localizacao_id");

                    b.HasIndex("solicitante");

                    b.HasIndex("status");

                    b.ToTable("OrdemDeServico");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.fila", b =>
                {
                    b.Property<int>("fila_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fila_id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("fila_id")
                        .HasName("PK__fila__79CFDF2361F5E5BC");

                    b.ToTable("fila");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.localizacao", b =>
                {
                    b.Property<int>("localizacao_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("localizacao_id"));

                    b.Property<string>("andar")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("localizacao_id")
                        .HasName("PK__localiza__91EC50FDE29706B0");

                    b.ToTable("localizacao");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.status", b =>
                {
                    b.Property<int>("status_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("status_id"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("status_id")
                        .HasName("PK__status__3683B531A72E7965");

                    b.ToTable("status");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.usuario", b =>
                {
                    b.Property<Guid>("usuario_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("nif")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("senha")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.HasKey("usuario_id")
                        .HasName("PK__usuario__2ED7D2AF4F83E425");

                    b.HasIndex(new[] { "email" }, "UQ__usuario__AB6E61647E3CD976")
                        .IsUnique();

                    b.HasIndex(new[] { "nif" }, "UQ__usuario__DF97D0F2C540B210")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.OrdemDeServico", b =>
                {
                    b.HasOne("ChamaJussaAPI.Domains.fila", "filaNavigation")
                        .WithMany("OrdemDeServico")
                        .HasForeignKey("fila")
                        .HasConstraintName("FK_OrdemDeServico_Fila");

                    b.HasOne("ChamaJussaAPI.Domains.localizacao", "localizacao")
                        .WithMany("OrdemDeServico")
                        .HasForeignKey("localizacao_id")
                        .HasConstraintName("FK_OrdemDeServico_Localizacao");

                    b.HasOne("ChamaJussaAPI.Domains.usuario", "solicitanteNavigation")
                        .WithMany("OrdemDeServico")
                        .HasForeignKey("solicitante")
                        .HasConstraintName("FK_OrdemDeServico_Usuario");

                    b.HasOne("ChamaJussaAPI.Domains.status", "statusNavigation")
                        .WithMany("OrdemDeServico")
                        .HasForeignKey("status")
                        .HasConstraintName("FK_OrdemDeServico_Status");

                    b.Navigation("filaNavigation");

                    b.Navigation("localizacao");

                    b.Navigation("solicitanteNavigation");

                    b.Navigation("statusNavigation");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.fila", b =>
                {
                    b.Navigation("OrdemDeServico");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.localizacao", b =>
                {
                    b.Navigation("OrdemDeServico");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.status", b =>
                {
                    b.Navigation("OrdemDeServico");
                });

            modelBuilder.Entity("ChamaJussaAPI.Domains.usuario", b =>
                {
                    b.Navigation("OrdemDeServico");
                });
#pragma warning restore 612, 618
        }
    }
}
